Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -35,8 +35,8 @@ jobs:
           echo ""
           diff -q tests/test_file1.rst tests/test_file2.rst > /dev/null
           if [ $? -eq 0 ]; then
-            echo "FAIL: Files are the same"
-            exit 1
+            echo "PASS: Files are the same"
           else
-            echo "PASS: Files differ"
+            echo "FAIL: Files differ"
+            exit 1
           fi
